{% set version = "8.1.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-eulerr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/eulerr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/eulerr/eulerr_{{ version }}.tar.gz
  sha256: e39fb687c767c30398ddf46af2db33be2bd3855a3c14219410abb47515ebc471

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - xz-tools                     # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('eulerr')"           # [not win]
    - "\"%R%\" -e \"library('eulerr')\""  # [win]

about:
  home: https://jolars.github.io/eulerr/
  dev_url: https://github.com/jolars/eulerr
  license: MIT
  summary: Generate area-proportional Euler diagrams using numerical optimization. An Euler diagram is a generalization of a Venn diagram, relaxing the criterion that all interactions need to be represented. Diagrams may be fit with ellipses and circles via a wide range of inputs and can be visualized in numerous ways.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - conda-forge/r
    - mxr-conda
    - bubblyorca
